// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("MovieResponses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Comedy",
                            Director = "Akiva Shaffer",
                            Edited = false,
                            LentTo = "",
                            Notes = "My name is Rod",
                            Rating = "PG-13",
                            Title = "Hot Rod",
                            Year = 2007
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Action/Sci-Fi",
                            Director = "Richard Marquand",
                            Edited = true,
                            LentTo = "Brett",
                            Notes = "Hit it Chewy!",
                            Rating = "PG",
                            Title = "Star Wars: Return of the Jedi",
                            Year = 1983
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Family/Adventure",
                            Director = "Andrew Stanton",
                            Edited = false,
                            LentTo = "Conner",
                            Notes = "Wallaby Way Sydney",
                            Rating = "G",
                            Title = "Finding Nemo",
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
